name: sedigram
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 600
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
