name: sedigram
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_storage_path: ^1.0.4
  intl: any
  json_annotation: ^4.8.1


dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  very_good_analysis: ^4.0.0+1
flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 600
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
