name: sedigram
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.12.2
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_storage: ^11.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  flutter_storage_path: ^1.0.4
  google_sign_in: ^6.1.5
  image_cropper: ^5.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  path: ^1.8.3
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  uuid: ^4.1.0


dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/sedigram_Icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/g.png
    - assets/icon/sedigram_Icon.png
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 600
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
